apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: loghouse
    meta.helm.sh/release-namespace: logging-monitoring
  labels:
    app.kubernetes.io/managed-by: Helm
  name: loghouse
  namespace: logging-monitoring

spec:
  clusterIP: 10.233.12.240
  clusterIPs:
  - 10.233.12.240
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 32519
      protocol: TCP
  selector:
    component: loghouse
  externalIPs:
    - 158.160.13.59
    - 158.160.4.109
  sessionAffinity: None
  type: NodePort